# Generated by Django 3.1.7 on 2021-02-24 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seen', '0002_auto_20210224_0809'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='seen_category',
        ),
        migrations.AlterModelTable(
            name='watchedobject',
            table='watched_object',
        ),
    ]
