# Generated by Django 3.1.7 on 2021-02-24 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seen', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedobject',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='snippets',
                                    to='auth.user'),
            preserve_default=False,
        ),
    ]
